TOKEN = "7537139368:AAEwVe80Qw-j8wff_GsDotBSf1UldHDRa7g"

class_names_en = ['Achaemenid architecture', 'American Foursquare architecture', 'American craftsman style', 'Ancient Egyptian architecture', 'Andean Baroque Architecture', 'Art Deco architecture', 'Art Nouveau architecture', 'Baroque architecture', 'Bauhaus architecture', 'Beaux-Arts architecture', 'Blobitecture', 'Brutalism', 'Byzantine architecture', 'Chicago school architecture', 'Classicism', 'Colonial Revival archtecture', 'Colonial architecture', 'Deconstructivism', 'Earthquake Baroque Architecture', 'Eco-architecture', 'Edwardian architecture', 'French Renaissance Architecture', 'Georgian architecture', 'Gothic architecture', 'Greek Revival architecture', 'Herodian architecture', 'International style', 'Mannerist Architecture', 'Medieval Architecture', 'Modern', 'Neo-futurism architecture', 'Norman Architecture', 'Northern Renaissance Architecture', 'Novelty architecture', 'Orientalism Architecture', 'Palladian architecture', 'Postmodern architecture', 'Queen Anne architecture', 'Rococo Architecture', 'Roman Classical architecture', 'Romanesque architecture', 'Russian Baroque Architecture', 'Russian Revival architecture', 'Sicilian Baroque Architecture', 'Spanish Colonial Architecture', 'Spanish Renaissance Architecture', 'Tudor Revival architecture', 'Venetian Gothic Architecture']

class_names_ua = [
    'Ахеменідська архітектура',
    'Американська архітектура чотирикутника',
    'Американський ремісничий стиль',
    'Стародавня єгипетська архітектура',
    'Андійська барокова архітектура',
    'Архітектура ар-деко',
    'Архітектура ар-нуво',
    'Барокова архітектура',
    'Архітектура Баухаус',
    'Архітектура боз-ар',
    'Блобітектура',
    'Бруталізм',
    'Візантійська архітектура',
    'Архітектура Чиказької школи',
    'Класицизм',
    'Колоніальний ренесанс',
    'Колоніальна архітектура',
    'Деконструктивізм',
    'Сейсмічне бароко',
    'Еко-архітектура',
    'Едвардіанська архітектура',
    'Французький ренесанс',
    'Георгіанська архітектура',
    'Готична архітектура',
    'Архітектура грецького відродження',
    'Іродіанська архітектура',
    'Інтернаціональний стиль',
    'Ман’єристська архітектура',
    'Середньовічна архітектура',
    'Сучасна архітектура',
    'Неофутуризм',
    'Норманська архітектура',
    'Архітектура північного ренесансу',
    'Новелті-архітектура',
    'Орієнталістська архітектура',
    'Палладіанська архітектура',
    'Постмодернізм',
    'Архітектура королеви Анни',
    'Рококо',
    'Римська класична архітектура',
    'Романська архітектура',
    'Російське бароко',
    'Російський ренесанс',
    'Сицилійське бароко',
    'Іспанська колоніальна архітектура',
    'Іспанський ренесанс',
    'Архітектура Тюдорівського відродження',
    'Венеційська готика'
]
